# -*- coding: utf-8 -*-
"""taller 7 (clase).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fdLJkA4wexEbJrEpOKQxcVc47YXxIZrp
"""

class Nodo():
  def __init__(self, valor):
    self.valor = valor
    self.siguiente = None

  def __repr__(self) -> str:
    return f"<Nodo{self.valor}>"

nodo1 = Nodo(1)
nodo2 = Nodo(2)
nodo3 = Nodo(3)
nodo4 = Nodo(4)
nodo5 = Nodo(5)

nodo1.siguiente = nodo2
nodo2.siguiente = nodo3
nodo3.siguiente = nodo4
nodo4.siguiente = nodo5
nodo5.siguiente = nodo2

def detectar_ciclo(lista):
  tortuga = lista
  liebre = lista

  while liebre and liebre.siguiente and tortuga:
    tortuga = tortuga.siguiente
    liebre = liebre.siguiente.siguiente

    if tortuga == liebre:
      print(tortuga, liebre)
      break

  liebre = lista

  while liebre != tortuga:
    liebre = liebre.siguiente
    tortuga = tortuga.siguiente
    print(tortuga, liebre)

  return False

detectar_ciclo(nodo1)